import { SliderConfig } from "./types";

export const YEARS = [2025, 2026, 2027, 2028, 2029];

export const SLIDERS: SliderConfig[] = [
  // ── Income Tax ──────────────────────────────────────────────
  {
    key: "personal_allowance",
    label: "Personal Allowance",
    section: "Income Tax",
    path: ["income_tax", "personal_allowance"],
    min: 0,
    max: 25000,
    step: 100,
    format: "currency",
  },
  {
    key: "pa_taper_threshold",
    label: "PA Taper Threshold",
    section: "Income Tax",
    path: ["income_tax", "pa_taper_threshold"],
    min: 50000,
    max: 200000,
    step: 1000,
    format: "currency",
  },
  {
    key: "pa_taper_rate",
    label: "PA Taper Rate",
    section: "Income Tax",
    path: ["income_tax", "pa_taper_rate"],
    min: 0,
    max: 1,
    step: 0.05,
    format: "percent",
  },
  {
    key: "basic_rate",
    label: "Basic Rate",
    section: "Income Tax",
    path: ["income_tax", "uk_brackets", "0", "rate"],
    min: 0,
    max: 0.5,
    step: 0.01,
    format: "percent",
  },
  {
    key: "basic_rate_threshold",
    label: "Basic Rate Threshold",
    section: "Income Tax",
    path: ["income_tax", "uk_brackets", "0", "threshold"],
    min: 0,
    max: 100000,
    step: 1000,
    format: "currency",
  },
  {
    key: "higher_rate",
    label: "Higher Rate",
    section: "Income Tax",
    path: ["income_tax", "uk_brackets", "1", "rate"],
    min: 0,
    max: 0.7,
    step: 0.01,
    format: "percent",
  },
  {
    key: "higher_rate_threshold",
    label: "Higher Rate Threshold",
    section: "Income Tax",
    path: ["income_tax", "uk_brackets", "1", "threshold"],
    min: 0,
    max: 200000,
    step: 1000,
    format: "currency",
  },
  {
    key: "additional_rate",
    label: "Additional Rate",
    section: "Income Tax",
    path: ["income_tax", "uk_brackets", "2", "rate"],
    min: 0,
    max: 0.8,
    step: 0.01,
    format: "percent",
  },
  {
    key: "additional_rate_threshold",
    label: "Additional Rate Threshold",
    section: "Income Tax",
    path: ["income_tax", "uk_brackets", "2", "threshold"],
    min: 0,
    max: 300000,
    step: 1000,
    format: "currency",
  },
  {
    key: "dividend_allowance",
    label: "Dividend Allowance",
    section: "Income Tax",
    path: ["income_tax", "dividend_allowance"],
    min: 0,
    max: 5000,
    step: 100,
    format: "currency",
  },
  {
    key: "dividend_basic_rate",
    label: "Dividend Basic Rate",
    section: "Income Tax",
    path: ["income_tax", "dividend_basic_rate"],
    min: 0,
    max: 0.5,
    step: 0.005,
    format: "percent",
  },
  {
    key: "dividend_higher_rate",
    label: "Dividend Higher Rate",
    section: "Income Tax",
    path: ["income_tax", "dividend_higher_rate"],
    min: 0,
    max: 0.6,
    step: 0.005,
    format: "percent",
  },
  {
    key: "dividend_additional_rate",
    label: "Dividend Additional Rate",
    section: "Income Tax",
    path: ["income_tax", "dividend_additional_rate"],
    min: 0,
    max: 0.7,
    step: 0.005,
    format: "percent",
  },
  {
    key: "savings_starter_rate_band",
    label: "Savings Starter Rate Band",
    section: "Income Tax",
    path: ["income_tax", "savings_starter_rate_band"],
    min: 0,
    max: 10000,
    step: 100,
    format: "currency",
  },
  {
    key: "marriage_allowance_max_fraction",
    label: "Marriage Allowance Fraction",
    section: "Income Tax",
    path: ["income_tax", "marriage_allowance_max_fraction"],
    min: 0,
    max: 0.5,
    step: 0.01,
    format: "percent",
  },

  // ── Scottish Income Tax ─────────────────────────────────────
  {
    key: "scot_starter_rate",
    label: "Starter Rate",
    section: "Scottish Income Tax",
    path: ["income_tax", "scottish_brackets", "0", "rate"],
    min: 0,
    max: 0.5,
    step: 0.01,
    format: "percent",
  },
  {
    key: "scot_starter_threshold",
    label: "Starter Rate Threshold",
    section: "Scottish Income Tax",
    path: ["income_tax", "scottish_brackets", "0", "threshold"],
    min: 0,
    max: 50000,
    step: 100,
    format: "currency",
  },
  {
    key: "scot_basic_rate",
    label: "Basic Rate",
    section: "Scottish Income Tax",
    path: ["income_tax", "scottish_brackets", "1", "rate"],
    min: 0,
    max: 0.5,
    step: 0.01,
    format: "percent",
  },
  {
    key: "scot_basic_threshold",
    label: "Basic Rate Threshold",
    section: "Scottish Income Tax",
    path: ["income_tax", "scottish_brackets", "1", "threshold"],
    min: 0,
    max: 50000,
    step: 100,
    format: "currency",
  },
  {
    key: "scot_intermediate_rate",
    label: "Intermediate Rate",
    section: "Scottish Income Tax",
    path: ["income_tax", "scottish_brackets", "2", "rate"],
    min: 0,
    max: 0.6,
    step: 0.01,
    format: "percent",
  },
  {
    key: "scot_intermediate_threshold",
    label: "Intermediate Rate Threshold",
    section: "Scottish Income Tax",
    path: ["income_tax", "scottish_brackets", "2", "threshold"],
    min: 0,
    max: 100000,
    step: 100,
    format: "currency",
  },
  {
    key: "scot_higher_rate",
    label: "Higher Rate",
    section: "Scottish Income Tax",
    path: ["income_tax", "scottish_brackets", "3", "rate"],
    min: 0,
    max: 0.7,
    step: 0.01,
    format: "percent",
  },
  {
    key: "scot_higher_threshold",
    label: "Higher Rate Threshold",
    section: "Scottish Income Tax",
    path: ["income_tax", "scottish_brackets", "3", "threshold"],
    min: 0,
    max: 200000,
    step: 100,
    format: "currency",
  },
  {
    key: "scot_advanced_rate",
    label: "Advanced Rate",
    section: "Scottish Income Tax",
    path: ["income_tax", "scottish_brackets", "4", "rate"],
    min: 0,
    max: 0.8,
    step: 0.01,
    format: "percent",
  },
  {
    key: "scot_advanced_threshold",
    label: "Advanced Rate Threshold",
    section: "Scottish Income Tax",
    path: ["income_tax", "scottish_brackets", "4", "threshold"],
    min: 0,
    max: 250000,
    step: 100,
    format: "currency",
  },
  {
    key: "scot_top_rate",
    label: "Top Rate",
    section: "Scottish Income Tax",
    path: ["income_tax", "scottish_brackets", "5", "rate"],
    min: 0,
    max: 0.8,
    step: 0.01,
    format: "percent",
  },
  {
    key: "scot_top_threshold",
    label: "Top Rate Threshold",
    section: "Scottish Income Tax",
    path: ["income_tax", "scottish_brackets", "5", "threshold"],
    min: 0,
    max: 300000,
    step: 1000,
    format: "currency",
  },

  // ── National Insurance ──────────────────────────────────────
  {
    key: "ni_primary_threshold",
    label: "Primary Threshold",
    section: "National Insurance",
    path: ["national_insurance", "primary_threshold_annual"],
    min: 0,
    max: 25000,
    step: 100,
    format: "currency",
  },
  {
    key: "ni_upper_earnings_limit",
    label: "Upper Earnings Limit",
    section: "National Insurance",
    path: ["national_insurance", "upper_earnings_limit_annual"],
    min: 0,
    max: 100000,
    step: 1000,
    format: "currency",
  },
  {
    key: "ni_main_rate",
    label: "Employee Main Rate",
    section: "National Insurance",
    path: ["national_insurance", "main_rate"],
    min: 0,
    max: 0.2,
    step: 0.005,
    format: "percent",
  },
  {
    key: "ni_additional_rate",
    label: "Employee Additional Rate",
    section: "National Insurance",
    path: ["national_insurance", "additional_rate"],
    min: 0,
    max: 0.1,
    step: 0.005,
    format: "percent",
  },
  {
    key: "ni_secondary_threshold",
    label: "Employer Secondary Threshold",
    section: "National Insurance",
    path: ["national_insurance", "secondary_threshold_annual"],
    min: 0,
    max: 25000,
    step: 100,
    format: "currency",
  },
  {
    key: "ni_employer_rate",
    label: "Employer NI Rate",
    section: "National Insurance",
    path: ["national_insurance", "employer_rate"],
    min: 0,
    max: 0.25,
    step: 0.005,
    format: "percent",
  },
  {
    key: "ni_class2_flat_rate",
    label: "Class 2 Weekly Rate",
    section: "National Insurance",
    path: ["national_insurance", "class2_flat_rate_weekly"],
    min: 0,
    max: 10,
    step: 0.05,
    format: "currency",
  },
  {
    key: "ni_class4_lower",
    label: "Class 4 Lower Profits Limit",
    section: "National Insurance",
    path: ["national_insurance", "class4_lower_profits_limit"],
    min: 0,
    max: 25000,
    step: 100,
    format: "currency",
  },
  {
    key: "ni_class4_upper",
    label: "Class 4 Upper Profits Limit",
    section: "National Insurance",
    path: ["national_insurance", "class4_upper_profits_limit"],
    min: 0,
    max: 100000,
    step: 1000,
    format: "currency",
  },
  {
    key: "ni_class4_main_rate",
    label: "Class 4 Main Rate",
    section: "National Insurance",
    path: ["national_insurance", "class4_main_rate"],
    min: 0,
    max: 0.2,
    step: 0.005,
    format: "percent",
  },
  {
    key: "ni_class4_additional_rate",
    label: "Class 4 Additional Rate",
    section: "National Insurance",
    path: ["national_insurance", "class4_additional_rate"],
    min: 0,
    max: 0.1,
    step: 0.005,
    format: "percent",
  },

  // ── Universal Credit ────────────────────────────────────────
  {
    key: "uc_standard_single_under25",
    label: "Standard (single <25, monthly)",
    section: "Universal Credit",
    path: ["universal_credit", "standard_allowance_single_under25"],
    min: 0,
    max: 800,
    step: 5,
    format: "currency",
  },
  {
    key: "uc_standard_single_over25",
    label: "Standard (single 25+, monthly)",
    section: "Universal Credit",
    path: ["universal_credit", "standard_allowance_single_over25"],
    min: 0,
    max: 800,
    step: 5,
    format: "currency",
  },
  {
    key: "uc_standard_couple_under25",
    label: "Standard (couple <25, monthly)",
    section: "Universal Credit",
    path: ["universal_credit", "standard_allowance_couple_under25"],
    min: 0,
    max: 1000,
    step: 5,
    format: "currency",
  },
  {
    key: "uc_standard_couple_over25",
    label: "Standard (couple 25+, monthly)",
    section: "Universal Credit",
    path: ["universal_credit", "standard_allowance_couple_over25"],
    min: 0,
    max: 1200,
    step: 5,
    format: "currency",
  },
  {
    key: "uc_child_element_first",
    label: "Child Element (first, monthly)",
    section: "Universal Credit",
    path: ["universal_credit", "child_element_first"],
    min: 0,
    max: 700,
    step: 5,
    format: "currency",
  },
  {
    key: "uc_child_element_subsequent",
    label: "Child Element (subsequent, monthly)",
    section: "Universal Credit",
    path: ["universal_credit", "child_element_subsequent"],
    min: 0,
    max: 700,
    step: 5,
    format: "currency",
  },
  {
    key: "uc_disabled_child_lower",
    label: "Disabled Child (lower, monthly)",
    section: "Universal Credit",
    path: ["universal_credit", "disabled_child_lower"],
    min: 0,
    max: 500,
    step: 5,
    format: "currency",
  },
  {
    key: "uc_disabled_child_higher",
    label: "Disabled Child (higher, monthly)",
    section: "Universal Credit",
    path: ["universal_credit", "disabled_child_higher"],
    min: 0,
    max: 1000,
    step: 5,
    format: "currency",
  },
  {
    key: "uc_lcwra_element",
    label: "LCWRA Element (monthly)",
    section: "Universal Credit",
    path: ["universal_credit", "lcwra_element"],
    min: 0,
    max: 800,
    step: 5,
    format: "currency",
  },
  {
    key: "uc_carer_element",
    label: "Carer Element (monthly)",
    section: "Universal Credit",
    path: ["universal_credit", "carer_element"],
    min: 0,
    max: 500,
    step: 5,
    format: "currency",
  },
  {
    key: "uc_taper_rate",
    label: "Taper Rate",
    section: "Universal Credit",
    path: ["universal_credit", "taper_rate"],
    min: 0,
    max: 1.0,
    step: 0.01,
    format: "percent",
  },
  {
    key: "uc_work_allowance_higher",
    label: "Work Allowance (higher, monthly)",
    section: "Universal Credit",
    path: ["universal_credit", "work_allowance_higher"],
    min: 0,
    max: 1200,
    step: 10,
    format: "currency",
  },
  {
    key: "uc_work_allowance_lower",
    label: "Work Allowance (lower, monthly)",
    section: "Universal Credit",
    path: ["universal_credit", "work_allowance_lower"],
    min: 0,
    max: 1000,
    step: 10,
    format: "currency",
  },
  {
    key: "uc_child_limit",
    label: "Child Limit",
    section: "Universal Credit",
    path: ["universal_credit", "child_limit"],
    min: 0,
    max: 10,
    step: 1,
    format: "currency",
  },
  {
    key: "uc_housing_cost_contribution",
    label: "Housing Cost Contribution (monthly)",
    section: "Universal Credit",
    path: ["universal_credit", "housing_cost_contribution"],
    min: 0,
    max: 200,
    step: 5,
    format: "currency",
  },

  // ── Child Benefit ───────────────────────────────────────────
  {
    key: "cb_eldest_weekly",
    label: "Eldest Child (weekly)",
    section: "Child Benefit",
    path: ["child_benefit", "eldest_weekly"],
    min: 0,
    max: 50,
    step: 0.5,
    format: "currency",
  },
  {
    key: "cb_additional_weekly",
    label: "Additional Child (weekly)",
    section: "Child Benefit",
    path: ["child_benefit", "additional_weekly"],
    min: 0,
    max: 40,
    step: 0.5,
    format: "currency",
  },
  {
    key: "hicbc_threshold",
    label: "HICBC Threshold",
    section: "Child Benefit",
    path: ["child_benefit", "hicbc_threshold"],
    min: 0,
    max: 150000,
    step: 1000,
    format: "currency",
  },
  {
    key: "hicbc_taper_end",
    label: "HICBC Taper End",
    section: "Child Benefit",
    path: ["child_benefit", "hicbc_taper_end"],
    min: 0,
    max: 200000,
    step: 1000,
    format: "currency",
  },

  // ── State Pension ───────────────────────────────────────────
  {
    key: "new_state_pension_weekly",
    label: "New State Pension (weekly)",
    section: "State Pension",
    path: ["state_pension", "new_state_pension_weekly"],
    min: 0,
    max: 400,
    step: 1,
    format: "currency",
  },
  {
    key: "old_basic_pension_weekly",
    label: "Old Basic Pension (weekly)",
    section: "State Pension",
    path: ["state_pension", "old_basic_pension_weekly"],
    min: 0,
    max: 300,
    step: 1,
    format: "currency",
  },

  // ── Pension Credit ──────────────────────────────────────────
  {
    key: "pc_standard_minimum_single",
    label: "Guarantee Credit (single, weekly)",
    section: "Pension Credit",
    path: ["pension_credit", "standard_minimum_single"],
    min: 0,
    max: 400,
    step: 1,
    format: "currency",
  },
  {
    key: "pc_standard_minimum_couple",
    label: "Guarantee Credit (couple, weekly)",
    section: "Pension Credit",
    path: ["pension_credit", "standard_minimum_couple"],
    min: 0,
    max: 600,
    step: 1,
    format: "currency",
  },
  {
    key: "pc_savings_credit_threshold_single",
    label: "Savings Credit Threshold (single)",
    section: "Pension Credit",
    path: ["pension_credit", "savings_credit_threshold_single"],
    min: 0,
    max: 400,
    step: 1,
    format: "currency",
  },
  {
    key: "pc_savings_credit_threshold_couple",
    label: "Savings Credit Threshold (couple)",
    section: "Pension Credit",
    path: ["pension_credit", "savings_credit_threshold_couple"],
    min: 0,
    max: 600,
    step: 1,
    format: "currency",
  },

  // ── Benefit Cap ─────────────────────────────────────────────
  {
    key: "benefit_cap_single_london",
    label: "Single (London)",
    section: "Benefit Cap",
    path: ["benefit_cap", "single_london"],
    min: 0,
    max: 30000,
    step: 100,
    format: "currency",
  },
  {
    key: "benefit_cap_single_outside",
    label: "Single (outside London)",
    section: "Benefit Cap",
    path: ["benefit_cap", "single_outside_london"],
    min: 0,
    max: 25000,
    step: 100,
    format: "currency",
  },
  {
    key: "benefit_cap_non_single_london",
    label: "Non-single (London)",
    section: "Benefit Cap",
    path: ["benefit_cap", "non_single_london"],
    min: 0,
    max: 40000,
    step: 100,
    format: "currency",
  },
  {
    key: "benefit_cap_non_single_outside",
    label: "Non-single (outside London)",
    section: "Benefit Cap",
    path: ["benefit_cap", "non_single_outside_london"],
    min: 0,
    max: 35000,
    step: 100,
    format: "currency",
  },
  {
    key: "benefit_cap_earnings_exemption",
    label: "Earnings Exemption Threshold",
    section: "Benefit Cap",
    path: ["benefit_cap", "earnings_exemption_threshold"],
    min: 0,
    max: 20000,
    step: 100,
    format: "currency",
  },

  // ── Housing Benefit ─────────────────────────────────────────
  {
    key: "hb_withdrawal_rate",
    label: "Withdrawal Rate",
    section: "Housing Benefit",
    path: ["housing_benefit", "withdrawal_rate"],
    min: 0,
    max: 1,
    step: 0.01,
    format: "percent",
  },
  {
    key: "hb_pa_single_under25",
    label: "Personal Allowance (single <25, weekly)",
    section: "Housing Benefit",
    path: ["housing_benefit", "personal_allowance_single_under25"],
    min: 0,
    max: 150,
    step: 1,
    format: "currency",
  },
  {
    key: "hb_pa_single_25plus",
    label: "Personal Allowance (single 25+, weekly)",
    section: "Housing Benefit",
    path: ["housing_benefit", "personal_allowance_single_25_plus"],
    min: 0,
    max: 200,
    step: 1,
    format: "currency",
  },
  {
    key: "hb_pa_couple",
    label: "Personal Allowance (couple, weekly)",
    section: "Housing Benefit",
    path: ["housing_benefit", "personal_allowance_couple"],
    min: 0,
    max: 300,
    step: 1,
    format: "currency",
  },
  {
    key: "hb_child_allowance",
    label: "Child Allowance (weekly)",
    section: "Housing Benefit",
    path: ["housing_benefit", "child_allowance"],
    min: 0,
    max: 200,
    step: 1,
    format: "currency",
  },
  {
    key: "hb_family_premium",
    label: "Family Premium (weekly)",
    section: "Housing Benefit",
    path: ["housing_benefit", "family_premium"],
    min: 0,
    max: 50,
    step: 0.5,
    format: "currency",
  },

  // ── Tax Credits ─────────────────────────────────────────────
  {
    key: "wtc_basic_element",
    label: "WTC Basic Element",
    section: "Tax Credits",
    path: ["tax_credits", "wtc_basic_element"],
    min: 0,
    max: 5000,
    step: 50,
    format: "currency",
  },
  {
    key: "wtc_couple_element",
    label: "WTC Couple Element",
    section: "Tax Credits",
    path: ["tax_credits", "wtc_couple_element"],
    min: 0,
    max: 5000,
    step: 50,
    format: "currency",
  },
  {
    key: "wtc_lone_parent_element",
    label: "WTC Lone Parent Element",
    section: "Tax Credits",
    path: ["tax_credits", "wtc_lone_parent_element"],
    min: 0,
    max: 5000,
    step: 50,
    format: "currency",
  },
  {
    key: "wtc_30_hour_element",
    label: "WTC 30-hour Element",
    section: "Tax Credits",
    path: ["tax_credits", "wtc_30_hour_element"],
    min: 0,
    max: 2000,
    step: 50,
    format: "currency",
  },
  {
    key: "ctc_child_element",
    label: "CTC Child Element",
    section: "Tax Credits",
    path: ["tax_credits", "ctc_child_element"],
    min: 0,
    max: 7000,
    step: 50,
    format: "currency",
  },
  {
    key: "ctc_family_element",
    label: "CTC Family Element",
    section: "Tax Credits",
    path: ["tax_credits", "ctc_family_element"],
    min: 0,
    max: 2000,
    step: 50,
    format: "currency",
  },
  {
    key: "ctc_disabled_child_element",
    label: "CTC Disabled Child Element",
    section: "Tax Credits",
    path: ["tax_credits", "ctc_disabled_child_element"],
    min: 0,
    max: 8000,
    step: 50,
    format: "currency",
  },
  {
    key: "ctc_severely_disabled_child_element",
    label: "CTC Severely Disabled Child Element",
    section: "Tax Credits",
    path: ["tax_credits", "ctc_severely_disabled_child_element"],
    min: 0,
    max: 4000,
    step: 50,
    format: "currency",
  },
  {
    key: "tc_income_threshold",
    label: "Income Threshold",
    section: "Tax Credits",
    path: ["tax_credits", "income_threshold"],
    min: 0,
    max: 15000,
    step: 100,
    format: "currency",
  },
  {
    key: "tc_taper_rate",
    label: "Taper Rate",
    section: "Tax Credits",
    path: ["tax_credits", "taper_rate"],
    min: 0,
    max: 1,
    step: 0.01,
    format: "percent",
  },

  // ── Council Tax Reduction ───────────────────────────────────
  {
    key: "ctr_taper_rate",
    label: "Taper Rate",
    section: "Council Tax Reduction",
    path: ["council_tax_reduction", "taper_rate"],
    min: 0,
    max: 1,
    step: 0.01,
    format: "percent",
  },
  {
    key: "ctr_pa_single_under25",
    label: "Personal Allowance (single <25, weekly)",
    section: "Council Tax Reduction",
    path: ["council_tax_reduction", "personal_allowance_single_under25"],
    min: 0,
    max: 150,
    step: 1,
    format: "currency",
  },
  {
    key: "ctr_pa_single_25plus",
    label: "Personal Allowance (single 25+, weekly)",
    section: "Council Tax Reduction",
    path: ["council_tax_reduction", "personal_allowance_single_25_plus"],
    min: 0,
    max: 200,
    step: 1,
    format: "currency",
  },
  {
    key: "ctr_pa_couple",
    label: "Personal Allowance (couple, weekly)",
    section: "Council Tax Reduction",
    path: ["council_tax_reduction", "personal_allowance_couple"],
    min: 0,
    max: 300,
    step: 1,
    format: "currency",
  },
  {
    key: "ctr_child_allowance",
    label: "Child Allowance (weekly)",
    section: "Council Tax Reduction",
    path: ["council_tax_reduction", "child_allowance"],
    min: 0,
    max: 200,
    step: 1,
    format: "currency",
  },
  {
    key: "ctr_family_premium",
    label: "Family Premium (weekly)",
    section: "Council Tax Reduction",
    path: ["council_tax_reduction", "family_premium"],
    min: 0,
    max: 50,
    step: 0.5,
    format: "currency",
  },

  // ── Scottish Child Payment ──────────────────────────────────
  {
    key: "scp_weekly_amount",
    label: "Weekly Amount",
    section: "Scottish Child Payment",
    path: ["scottish_child_payment", "weekly_amount"],
    min: 0,
    max: 50,
    step: 0.5,
    format: "currency",
  },
  {
    key: "scp_max_age",
    label: "Max Age",
    section: "Scottish Child Payment",
    path: ["scottish_child_payment", "max_age"],
    min: 0,
    max: 18,
    step: 1,
    format: "currency",
  },
];

export const SECTIONS = [
  "Income Tax",
  "Scottish Income Tax",
  "National Insurance",
  "Universal Credit",
  "Child Benefit",
  "State Pension",
  "Pension Credit",
  "Benefit Cap",
  "Housing Benefit",
  "Tax Credits",
  "Council Tax Reduction",
  "Scottish Child Payment",
];

export const API_BASE = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";
