"""Python wrapper for the PolicyEngine UK Rust microsimulation binary."""

from policyengine_uk_compiled.models import (
    SimulationConfig,
    SimulationResult,
    BudgetaryImpact,
    IncomeBreakdown,
    ProgramBreakdown,
    Caseloads,
    DecileImpact,
    WinnersLosers,
    IncomeTaxParams,
    NationalInsuranceParams,
    UniversalCreditParams,
    ChildBenefitParams,
    StatePensionParams,
    PensionCreditParams,
    BenefitCapParams,
    HousingBenefitParams,
    TaxCreditsParams,
    ScottishChildPaymentParams,
    UcMigrationRates,
    Parameters,
)
from policyengine_uk_compiled.engine import Simulation

__all__ = [
    "Simulation",
    "SimulationConfig",
    "SimulationResult",
    "BudgetaryImpact",
    "IncomeBreakdown",
    "ProgramBreakdown",
    "Caseloads",
    "DecileImpact",
    "WinnersLosers",
    "IncomeTaxParams",
    "NationalInsuranceParams",
    "UniversalCreditParams",
    "ChildBenefitParams",
    "StatePensionParams",
    "PensionCreditParams",
    "BenefitCapParams",
    "HousingBenefitParams",
    "TaxCreditsParams",
    "ScottishChildPaymentParams",
    "UcMigrationRates",
    "Parameters",
]
