"""
Upload clean FRS CSV files to the Modal Volume.

Usage:
    python api/upload_frs.py <path-to-frs-clean-dir>

The directory should contain: persons.csv, benunits.csv, households.csv
(generated by: policyengine-uk --extract-frs <output-dir> --frs <raw-frs-dir>)

This only needs to be run once (or when the FRS data changes).
"""

import sys
from pathlib import Path
import modal

FRS_VOLUME_NAME = "policyengine-uk-frs"
REMOTE_PATH = "/data/frs_clean"
EXPECTED_FILES = {"persons.csv", "benunits.csv", "households.csv"}


def upload(local_dir: Path) -> None:
    missing = EXPECTED_FILES - {f.name for f in local_dir.iterdir() if f.is_file()}
    if missing:
        print(f"Error: missing files in {local_dir}: {missing}", file=sys.stderr)
        sys.exit(1)

    volume = modal.Volume.from_name(FRS_VOLUME_NAME, create_if_missing=True)

    print(f"Uploading FRS clean CSVs from {local_dir} → Modal Volume '{FRS_VOLUME_NAME}':{REMOTE_PATH}")
    with volume.batch_upload(force=True) as batch:
        for csv_file in local_dir.glob("*.csv"):
            remote = f"{REMOTE_PATH}/{csv_file.name}"
            batch.put_file(str(csv_file), remote)
            print(f"  {csv_file.name} → {remote}")

    print("Done. Volume contents:")
    for entry in volume.listdir(REMOTE_PATH):
        print(f"  {entry.path}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(f"Usage: python {sys.argv[0]} <frs-clean-dir>", file=sys.stderr)
        sys.exit(1)

    local_dir = Path(sys.argv[1])
    if not local_dir.is_dir():
        print(f"Error: {local_dir} is not a directory", file=sys.stderr)
        sys.exit(1)

    upload(local_dir)
